### ISSUE TITLE
Silently fails when stowing if source and destination are in different drives.

### ISSUE THREAD

**Issue by noc7c9** [arecarn/dploy#2]
```
P:\dotfiles>dploy stow vim p:\test
dploy stow: link p:\test\.vim => ..\dotfiles\vim\.vim
dploy stow: link p:\test\.vimrc => ..\dotfiles\vim\.vimrc

P:\dotfiles>dploy stow vim c:\Users\user

P:\dotfiles>
```

As you can see stowing from `P:\dotfiles\vim` to `P:\test` works fine. But changing the destination to `C:\Users\user` does nothing.

Update:
I set up a directory junction `C:\User\user\dotfiles => P:\dotfiles` and stowing from there works fine, but it is a hassle.

**Comment by arecarn** [comment]
Interesting, I'll take a look

**Comment by arecarn** [comment]
Let me know if that fixes it for you.

**Comment by noc7c9** [comment]
I have to pass in the absolute path, otherwise it creates relative symlinks that don't work.
```
P:\dotfiles>dploy --dry-run stow vim C:\Users\user
dploy stow: link C:\Users\user\.vim => vim\.vim
dploy stow: link C:\Users\user\.vimrc => vim\.vimrc

P:\dotfiles>dploy --dry-run stow p:\dotfiles\vim C:\Users\user
dploy stow: link C:\Users\user\.vim => p:\dotfiles\vim\.vim
dploy stow: link C:\Users\user\.vimrc => p:\dotfiles\vim\.vimrc
```

Making the obvious change at [utils.py#L65](https://github.com/arecarn/dploy/blob/f5238c5cf6f8d66f0c4bff502f35791a71d0dd12/dploy/utils.py#L65) fixes things though.
```py
relative_path = os.path.abspath(str(path))
```
```
P:\dotfiles>dploy --dry-run stow vim C:\Users\user
dploy stow: link C:\Users\user\.vim => P:\dotfiles\vim\.vim
dploy stow: link C:\Users\user\.vimrc => P:\dotfiles\vim\.vimrc
```

**Comment by arecarn** [comment]
Good catch!
I've incorporated a version of your fix. Let me know if everything works for you. 
Thanks for your help.

**Comment by noc7c9** [comment]
It works perfectly now, thanks.
