### ISSUE TITLE
Pytest leaves some garbage in tmpdir

### ISSUE THREAD

**Issue by harkabeeparolus** [arecarn/dploy#6]
After running **pytest**, there are some files and folders left in the tmpdir used by pytest. I have verified this on Linux and macOS, but I have not tried it on Windows.

I suspect this is a result of the function `remove_execute_permission()` in `tests/utils.py`, and maybe also _remove_read_ and _remove_write_.

On Python <= 3.7, this is mostly invisible, because **pytest** doesn't complain. But on Python >= 3.8, after all the pytest tests have passed, this leads to warnings such as:

```
/users/traal/python/dploy/.venv/lib/python3.9/site-packages/_pytest/pathlib.py:87: PytestWarning: (rm_rf) unknown function <built-in function lstat> when removing /tmp/pytest-of-traal/garbage-fa89668f-46fb-4f9e-991b-55f88c40df17/test_unstow_folding_with_multi3/source_b/aaa:
<class 'PermissionError'>: [Errno 13] Permission denied: 'aaa'
  warnings.warn(
```

Regardless of Python version, here's an example of the underlying problem:

```
❯ ( cd /tmp/pytest-of-traal/pytest-current && find >/dev/null )
find: ‘./test_unstow_folding_with_multi3/source_b/aaa’: Permission denied
find: ‘./test_stow_with_write_only_sour1/source_a/aaa’: Permission denied
find: ‘./test_stow_with_source_dir_with0/source_a/aaa/ccc’: Permission denied
find: ‘./test_stow_unfolding_with_write0/source_a/aaa’: Permission denied
find: ‘./test_unstow_with_write_only_so0/source_a’: Permission denied
find: ‘./test_stow_with_write_only_sour0/source_a’: Permission denied
find: ‘./test_stow_with_source_with_no_0/source_a/aaa’: Permission denied
find: ‘./test_unstow_with_write_only_de0/source_a/aaa’: Permission denied
find: ‘./test_stow_unfolding_with_first0/source_a/aaa’: Permission denied
```

I am not sure how to fix this, because I don't know enough about pytest yet. I think that the removed permissions should be restored somehow, after the tests are run, so that the files can be removed cleanly.

**Comment by arecarn** [comment]
As you've noted I need to adjust the tests to restore the permissions before they exit. Here's and example of how we can do it with a fixture: https://github.com/pytest-dev/pytest/issues/7821#issuecomment-701420062

**Comment by harkabeeparolus** [comment]
I finally got around to completing this.

I did update the fixtures that create directories, similar to what you suggested.
